import type { Question } from "./types";

// Next.js supports importing JSON in the app directory.
// We keep this in a separate module so the UI has a single stable import.
import bank from "../content/question-bank.json";

type Seed = {
  id: string;
  framework: "predictive" | "agile" | "hybrid";
  domain: "people" | "process" | "business";
  topic: string;
  correctStatement: string;
  distractors: [string, string, string];
  textbookReference: string;
  formalDefinition: string;
  nigerianAnalogy: string;
};

const EXPANDED_SEEDS: Seed[] = [
  {
    id: "predictive_people_communications_plan",
    framework: "predictive",
    domain: "people",
    topic: "communications planning",
    correctStatement: "Tailor communication frequency, format, and channels to stakeholder needs.",
    distractors: [
      "Use one standard report format for every stakeholder regardless of role.",
      "Communicate only when there is an issue to escalate.",
      "Allow each team member to communicate independently without alignment.",
    ],
    textbookReference: "PMBOK Guide 7th: Stakeholders and communication tailoring",
    formalDefinition: "Communication planning defines who needs what information, when, and how.",
    nigerianAnalogy: "You brief elders, friends, and vendors differently during a large family event.",
  },
  {
    id: "predictive_people_conflict_resolution",
    framework: "predictive",
    domain: "people",
    topic: "conflict resolution",
    correctStatement: "Resolve conflict early by focusing on interests, facts, and project outcomes.",
    distractors: [
      "Ignore conflict so the team can self-correct over time.",
      "Always escalate conflict immediately to the sponsor.",
      "Use authority to decide quickly without listening to both sides.",
    ],
    textbookReference: "PMBOK 6th: Manage Team conflict techniques",
    formalDefinition: "Constructive conflict management protects collaboration and performance.",
    nigerianAnalogy: "Settle kitchen disputes early before wedding food quality drops.",
  },
  {
    id: "predictive_people_team_charter",
    framework: "predictive",
    domain: "people",
    topic: "team charter",
    correctStatement: "Define team values, working agreements, and decision rules early.",
    distractors: [
      "Leave behavior expectations informal to reduce bureaucracy.",
      "Use only individual KPIs instead of shared agreements.",
      "Document charter after project execution starts.",
    ],
    textbookReference: "PMBOK 6th: Develop Team, team charter concept",
    formalDefinition: "A team charter clarifies norms, expectations, and collaboration standards.",
    nigerianAnalogy: "Family planning meetings run better when everyone agrees ground rules upfront.",
  },
  {
    id: "predictive_people_stakeholder_mapping",
    framework: "predictive",
    domain: "people",
    topic: "stakeholder mapping",
    correctStatement: "Use influence and interest analysis to prioritize engagement strategy.",
    distractors: [
      "Rank stakeholders only by job title.",
      "Focus communication only on supportive stakeholders.",
      "Treat all stakeholders as equal in influence and impact.",
    ],
    textbookReference: "PMBOK 6th: Identify Stakeholders",
    formalDefinition: "Stakeholder mapping classifies stakeholders for targeted engagement.",
    nigerianAnalogy: "You update key sponsors first, then wider family and vendors.",
  },
  {
    id: "predictive_people_resource_negotiation",
    framework: "predictive",
    domain: "people",
    topic: "resource negotiation",
    correctStatement: "Negotiate resource commitments using priority, timing, and business impact data.",
    distractors: [
      "Request full-time resources without clarifying workload timing.",
      "Escalate before discussing constraints with functional managers.",
      "Assign work immediately even if required skills are missing.",
    ],
    textbookReference: "PMBOK 6th: Acquire Resources",
    formalDefinition: "Resource negotiation balances project needs with organizational constraints.",
    nigerianAnalogy: "Book your best decorator early with clear dates to avoid clashes.",
  },
  {
    id: "predictive_process_scope_baseline_control",
    framework: "predictive",
    domain: "process",
    topic: "scope baseline control",
    correctStatement: "Protect approved scope baseline through formal change control.",
    distractors: [
      "Allow informal scope additions when stakeholders request quickly.",
      "Update baseline weekly without approvals to stay flexible.",
      "Avoid documenting scope changes to save time.",
    ],
    textbookReference: "PMBOK 6th: Scope baseline and change control",
    formalDefinition: "Scope baseline is the approved project scope used for control.",
    nigerianAnalogy: "If guest list increases, you reapprove budget before buying more food.",
  },
  {
    id: "predictive_process_schedule_compression",
    framework: "predictive",
    domain: "process",
    topic: "schedule compression",
    correctStatement: "Use crashing or fast tracking only after analyzing cost and risk trade-offs.",
    distractors: [
      "Compress schedule by removing mandatory quality checks.",
      "Add overtime by default whenever a task slips.",
      "Fast track every activity simultaneously for speed.",
    ],
    textbookReference: "PMBOK 6th: Develop Schedule compression techniques",
    formalDefinition: "Schedule compression shortens duration while managing added risk or cost.",
    nigerianAnalogy: "You can hire extra cooks, but you must still protect food quality.",
  },
  {
    id: "predictive_process_quality_audit",
    framework: "predictive",
    domain: "process",
    topic: "quality audits",
    correctStatement: "Use audits to verify process compliance and identify improvement opportunities.",
    distractors: [
      "Run audits only after deliverables fail acceptance.",
      "Treat audits as fault-finding exercises for individuals.",
      "Skip audits when schedule pressure is high.",
    ],
    textbookReference: "PMBOK 6th: Manage Quality",
    formalDefinition: "Quality audits assess process effectiveness and compliance.",
    nigerianAnalogy: "Taste checks during cooking avoid embarrassment at serving time.",
  },
  {
    id: "predictive_process_risk_register_updates",
    framework: "predictive",
    domain: "process",
    topic: "risk register updates",
    correctStatement: "Continuously update risk register with responses, owners, and trigger conditions.",
    distractors: [
      "Freeze risk register after planning to keep consistency.",
      "Track only high-probability risks and ignore opportunities.",
      "Document risks without assigning owners.",
    ],
    textbookReference: "PMBOK 6th: Monitor Risks",
    formalDefinition: "Risk register is a living document used to track threats and opportunities.",
    nigerianAnalogy: "Keep updating your rainy-season backup plan as weather changes.",
  },
  {
    id: "predictive_process_procurement_evaluation",
    framework: "predictive",
    domain: "process",
    topic: "procurement source selection",
    correctStatement: "Evaluate sellers using weighted criteria aligned to project priorities.",
    distractors: [
      "Award contract to the lowest bid regardless of capability.",
      "Select sellers based on prior familiarity only.",
      "Delay evaluation criteria definition until proposals arrive.",
    ],
    textbookReference: "PMBOK 6th: Conduct Procurements",
    formalDefinition: "Source selection criteria balance price, quality, risk, and capability.",
    nigerianAnalogy: "Cheapest decorator is not always best for a high-profile wedding.",
  },
  {
    id: "predictive_business_benefits_traceability",
    framework: "predictive",
    domain: "business",
    topic: "benefits traceability",
    correctStatement: "Trace deliverables to intended benefits and strategic outcomes.",
    distractors: [
      "Treat project completion as success regardless of benefits realization.",
      "Measure only cost variance and ignore outcome metrics.",
      "Define benefits after transition to operations.",
    ],
    textbookReference: "PMBOK 7th: Value delivery system",
    formalDefinition: "Benefits traceability links outputs to measurable value outcomes.",
    nigerianAnalogy: "Buying a freezer matters only if it reduces spoilage and costs.",
  },
  {
    id: "predictive_business_compliance_gate",
    framework: "predictive",
    domain: "business",
    topic: "compliance gate checks",
    correctStatement: "Use governance gates to confirm compliance before major commitments.",
    distractors: [
      "Skip compliance checks for urgent deadlines.",
      "Run governance only at project closure.",
      "Delegate compliance decisions entirely to vendors.",
    ],
    textbookReference: "PMBOK 7th: Governance domain",
    formalDefinition: "Governance gates are decision points for oversight and compliance.",
    nigerianAnalogy: "Confirm permits before event setup to avoid shutdown risks.",
  },
  {
    id: "predictive_business_cost_baseline_forecast",
    framework: "predictive",
    domain: "business",
    topic: "cost forecast control",
    correctStatement: "Compare actuals against cost baseline and forecast EAC proactively.",
    distractors: [
      "Wait until funds are exhausted before forecasting.",
      "Track only planned budget and ignore actual spend.",
      "Adjust baseline monthly without approval.",
    ],
    textbookReference: "PMBOK 6th: Control Costs",
    formalDefinition: "Forecasting estimates final cost using current performance trends.",
    nigerianAnalogy: "Track spending weekly so celebration budget does not explode.",
  },
  {
    id: "predictive_business_change_impact_assessment",
    framework: "predictive",
    domain: "business",
    topic: "change impact assessment",
    correctStatement: "Assess scope, schedule, cost, risk, and benefits before approving changes.",
    distractors: [
      "Approve all customer changes to keep satisfaction high.",
      "Reject all changes after baseline freeze.",
      "Evaluate only schedule impact for speed.",
    ],
    textbookReference: "PMBOK 6th: Perform Integrated Change Control",
    formalDefinition: "Impact assessment evaluates the full implications of proposed changes.",
    nigerianAnalogy: "Adding 200 guests affects food, chairs, venue, transport, and security.",
  },
  {
    id: "predictive_business_lessons_repository",
    framework: "predictive",
    domain: "business",
    topic: "lessons learned repository",
    correctStatement: "Capture and reuse lessons throughout the project lifecycle, not only at closure.",
    distractors: [
      "Document lessons only if major failures occur.",
      "Store lessons informally in private notes.",
      "Wait until final report to identify improvements.",
    ],
    textbookReference: "PMBOK 6th: Manage Project Knowledge",
    formalDefinition: "Lessons learned records capture knowledge to improve future performance.",
    nigerianAnalogy: "Write down what worked this celebration so next one is smoother.",
  },
  {
    id: "agile_people_servant_leadership",
    framework: "agile",
    domain: "people",
    topic: "servant leadership",
    correctStatement: "Servant leaders remove impediments and enable team ownership.",
    distractors: [
      "Servant leaders assign every task detail daily.",
      "Servant leaders avoid stakeholder interaction.",
      "Servant leaders focus on individual heroics over team flow.",
    ],
    textbookReference: "PMI Agile Practice Guide: Servant leadership",
    formalDefinition: "Servant leadership prioritizes team enablement and value delivery.",
    nigerianAnalogy: "A good lead clears roadblocks so the team can deliver confidently.",
  },
  {
    id: "agile_people_psychological_safety",
    framework: "agile",
    domain: "people",
    topic: "psychological safety",
    correctStatement: "Create safety for dissent and learning to improve team decisions.",
    distractors: [
      "Avoid hard conversations to preserve harmony.",
      "Penalize failed experiments publicly.",
      "Restrict retrospectives to senior members only.",
    ],
    textbookReference: "PMI Agile Practice Guide: Team dynamics",
    formalDefinition: "Psychological safety supports candid dialogue and continuous improvement.",
    nigerianAnalogy: "People suggest better ideas when they are not afraid of ridicule.",
  },
  {
    id: "agile_people_collaborative_planning",
    framework: "agile",
    domain: "people",
    topic: "collaborative planning",
    correctStatement: "Plan with the team to improve realism, ownership, and commitment.",
    distractors: [
      "Planning should be done solely by the project manager.",
      "Backlog priorities should be hidden from the team.",
      "Commitments should ignore team capacity data.",
    ],
    textbookReference: "PMI Agile Practice Guide: Planning in agile",
    formalDefinition: "Collaborative planning aligns priorities with delivery capacity.",
    nigerianAnalogy: "Ask the full kitchen team before promising unrealistic menu timelines.",
  },
  {
    id: "agile_people_cross_functional_skills",
    framework: "agile",
    domain: "people",
    topic: "cross-functional team behavior",
    correctStatement: "Cross-functional teams reduce handoff delays and improve value flow.",
    distractors: [
      "Specialists should avoid supporting outside their core role.",
      "Handoffs between silos increase efficiency in agile delivery.",
      "Only leads should understand full workflow.",
    ],
    textbookReference: "PMI Agile Practice Guide: Team composition",
    formalDefinition: "Cross-functional teams own end-to-end delivery of increments.",
    nigerianAnalogy: "Shared chores prevent bottlenecks when preparing for large events.",
  },
  {
    id: "agile_people_coaching_feedback",
    framework: "agile",
    domain: "people",
    topic: "coaching feedback loops",
    correctStatement: "Use frequent coaching feedback to improve skills and outcomes incrementally.",
    distractors: [
      "Give feedback only at annual reviews.",
      "Focus feedback on blame for missed commitments.",
      "Avoid feedback to protect morale.",
    ],
    textbookReference: "PMI Agile Practice Guide: Agile coaching",
    formalDefinition: "Coaching feedback supports learning and adaptation in iterative delivery.",
    nigerianAnalogy: "Small corrections during rehearsal prevent mistakes on event day.",
  },
  {
    id: "agile_process_backlog_ordering",
    framework: "agile",
    domain: "process",
    topic: "backlog ordering",
    correctStatement: "Order backlog by value, risk, dependencies, and learning potential.",
    distractors: [
      "Order backlog by who requested items first.",
      "Keep all backlog items fixed once sprint planning begins.",
      "Prioritize only easy tasks to increase velocity optics.",
    ],
    textbookReference: "PMI Agile Practice Guide: Backlog prioritization",
    formalDefinition: "Backlog ordering maximizes value and reduces uncertainty.",
    nigerianAnalogy: "Buy high-impact market items first when budget and time are limited.",
  },
  {
    id: "agile_process_definition_of_ready",
    framework: "agile",
    domain: "process",
    topic: "definition of ready",
    correctStatement: "Use readiness criteria to reduce ambiguity before implementation starts.",
    distractors: [
      "Start every story immediately, even when acceptance criteria are unclear.",
      "Definition of ready replaces stakeholder engagement.",
      "Ready criteria should be decided by developers only.",
    ],
    textbookReference: "PMI Agile Practice Guide: Work item readiness",
    formalDefinition: "Definition of ready clarifies minimum conditions before work starts.",
    nigerianAnalogy: "Confirm ingredients before cooking to avoid mid-process surprises.",
  },
  {
    id: "agile_process_wip_limits",
    framework: "agile",
    domain: "process",
    topic: "work-in-progress limits",
    correctStatement: "Limit WIP to improve flow, focus, and cycle time predictability.",
    distractors: [
      "Maximize parallel tasks to show everyone is busy.",
      "Ignore blocked work and start new items continuously.",
      "Use WIP limits only for support teams, not projects.",
    ],
    textbookReference: "PMI Agile Practice Guide: Flow-based methods",
    formalDefinition: "WIP limits constrain active work to improve throughput and quality.",
    nigerianAnalogy: "Cook fewer dishes at once so each is done properly and on time.",
  },
  {
    id: "agile_process_acceptance_criteria",
    framework: "agile",
    domain: "process",
    topic: "acceptance criteria",
    correctStatement: "Clear acceptance criteria reduce rework and align stakeholder expectations.",
    distractors: [
      "Acceptance criteria should be optional for complex stories.",
      "Define acceptance only after coding is complete.",
      "QA alone should decide acceptance criteria.",
    ],
    textbookReference: "PMI Agile Practice Guide: Requirements and validation",
    formalDefinition: "Acceptance criteria define conditions a work item must meet.",
    nigerianAnalogy: "Agree what 'ready outfit' means before sewing begins.",
  },
  {
    id: "agile_process_iteration_review",
    framework: "agile",
    domain: "process",
    topic: "iteration review",
    correctStatement: "Use review events to inspect increment outcomes and adapt priorities.",
    distractors: [
      "Use reviews only to report completed points.",
      "Cancel reviews when sprint goals are missed.",
      "Keep stakeholders away from iteration demos.",
    ],
    textbookReference: "PMI Agile Practice Guide: Review and feedback",
    formalDefinition: "Iteration reviews validate product increments with stakeholders.",
    nigerianAnalogy: "Taste and adjust menu weekly instead of waiting for final event day.",
  },
  {
    id: "agile_business_value_hypotheses",
    framework: "agile",
    domain: "business",
    topic: "value hypothesis testing",
    correctStatement: "Deliver small increments to validate value assumptions with real users.",
    distractors: [
      "Build complete scope before any user validation.",
      "Assume business value from internal opinions only.",
      "Avoid experiments to protect schedule certainty.",
    ],
    textbookReference: "PMI Agile Practice Guide: Value and experimentation",
    formalDefinition: "Hypothesis-driven delivery reduces waste and improves value realization.",
    nigerianAnalogy: "Pilot new menu items before investing in full restaurant expansion.",
  },
  {
    id: "agile_business_release_planning",
    framework: "agile",
    domain: "business",
    topic: "release planning",
    correctStatement: "Plan releases around value milestones, dependency readiness, and risk.",
    distractors: [
      "Release based only on calendar dates.",
      "Bundle all backlog items into one large release.",
      "Release regardless of definition-of-done quality checks.",
    ],
    textbookReference: "PMI Agile Practice Guide: Release planning",
    formalDefinition: "Release planning sequences increments to optimize value and readiness.",
    nigerianAnalogy: "Deliver event preparations in waves, not one risky final rush.",
  },
  {
    id: "agile_business_customer_feedback_cycle",
    framework: "agile",
    domain: "business",
    topic: "customer feedback loops",
    correctStatement: "Embed frequent customer feedback to refine value priorities continuously.",
    distractors: [
      "Collect customer feedback only at project closure.",
      "Prioritize internal preferences over user outcomes.",
      "Treat feedback as optional once roadmap is approved.",
    ],
    textbookReference: "PMI Agile Practice Guide: Customer collaboration",
    formalDefinition: "Feedback loops align product direction with customer needs.",
    nigerianAnalogy: "Check guest reactions after each event phase and adjust quickly.",
  },
  {
    id: "agile_business_evidence_metrics",
    framework: "agile",
    domain: "business",
    topic: "evidence-based metrics",
    correctStatement: "Use outcome metrics, not just output metrics, to assess value delivered.",
    distractors: [
      "Measure only number of stories completed.",
      "Ignore customer adoption and satisfaction data.",
      "Use velocity as a standalone business value metric.",
    ],
    textbookReference: "PMBOK 7th: Measurement and uncertainty",
    formalDefinition: "Outcome metrics evaluate realized benefits and strategic impact.",
    nigerianAnalogy: "Count satisfied guests, not only number of dishes served.",
  },
  {
    id: "agile_business_product_vision_alignment",
    framework: "agile",
    domain: "business",
    topic: "product vision alignment",
    correctStatement: "Use a clear product vision to guide backlog trade-off decisions.",
    distractors: [
      "Allow each team member to define product direction independently.",
      "Change vision every sprint without stakeholder alignment.",
      "Prioritize features by loudest request only.",
    ],
    textbookReference: "PMI Agile Practice Guide: Product vision",
    formalDefinition: "A product vision aligns team and stakeholders around long-term value goals.",
    nigerianAnalogy: "A clear ceremony theme keeps all planning decisions consistent.",
  },
  {
    id: "hybrid_people_change_readiness",
    framework: "hybrid",
    domain: "people",
    topic: "change readiness assessment",
    correctStatement: "Assess culture, capability, and sponsorship readiness before hybrid rollout.",
    distractors: [
      "Launch hybrid practices without stakeholder readiness checks.",
      "Assume training is unnecessary for experienced teams.",
      "Treat resistance as non-compliance instead of feedback.",
    ],
    textbookReference: "PMBOK 7th: Tailoring and stakeholder engagement",
    formalDefinition: "Readiness assessment informs realistic adoption planning.",
    nigerianAnalogy: "Introduce new family routines gradually with buy-in from key voices.",
  },
  {
    id: "hybrid_people_decision_rights",
    framework: "hybrid",
    domain: "people",
    topic: "decision rights clarity",
    correctStatement: "Define which decisions are team-level versus governance-level.",
    distractors: [
      "Let all decisions escalate to steering committee.",
      "Allow teams to override compliance decisions freely.",
      "Avoid documenting decision boundaries to stay flexible.",
    ],
    textbookReference: "PMBOK 7th: Governance domain",
    formalDefinition: "Decision rights clarity reduces delays and accountability gaps.",
    nigerianAnalogy: "Know what planners decide versus what elders approve.",
  },
  {
    id: "hybrid_people_stakeholder_alignment",
    framework: "hybrid",
    domain: "people",
    topic: "stakeholder alignment cadence",
    correctStatement: "Use frequent demos plus formal governance updates to keep alignment.",
    distractors: [
      "Rely only on steering meetings for stakeholder visibility.",
      "Rely only on sprint demos for executive governance.",
      "Communicate major trade-offs only after implementation.",
    ],
    textbookReference: "PMI Agile Practice Guide: Hybrid engagement practices",
    formalDefinition: "Hybrid communication combines adaptive feedback and formal oversight.",
    nigerianAnalogy: "Share weekly prep progress and still hold key family approval meetings.",
  },
  {
    id: "hybrid_people_role_integration",
    framework: "hybrid",
    domain: "people",
    topic: "role integration",
    correctStatement: "Integrate PM, product, and governance roles with explicit collaboration rules.",
    distractors: [
      "Merge all roles into one person to reduce complexity.",
      "Keep roles isolated without cross-role planning.",
      "Assume role expectations are obvious without definition.",
    ],
    textbookReference: "PMBOK 7th: Team and stakeholder domains",
    formalDefinition: "Role integration aligns accountability across adaptive and predictive controls.",
    nigerianAnalogy: "Planner, treasurer, and coordinator must align responsibilities clearly.",
  },
  {
    id: "hybrid_people_conflict_between_methods",
    framework: "hybrid",
    domain: "people",
    topic: "method conflict resolution",
    correctStatement: "Resolve predictive-versus-agile disputes by aligning to outcomes and constraints.",
    distractors: [
      "Force one method universally regardless of context.",
      "Let each sub-team follow incompatible planning cycles.",
      "Ignore conflicts and expect maturity to emerge.",
    ],
    textbookReference: "PMBOK 7th: Tailoring principle",
    formalDefinition: "Hybrid conflict resolution balances adaptability with governance obligations.",
    nigerianAnalogy: "Blend tradition and modern style based on event goals and constraints.",
  },
  {
    id: "hybrid_process_governance_cadence",
    framework: "hybrid",
    domain: "process",
    topic: "governance cadence design",
    correctStatement: "Set governance cadence that supports learning cycles without losing control.",
    distractors: [
      "Use monthly governance only and stop iterative inspections.",
      "Use iterative ceremonies only and skip gate criteria.",
      "Change governance cadence ad hoc without rationale.",
    ],
    textbookReference: "PMBOK 7th: Governance and tailoring",
    formalDefinition: "Governance cadence defines timing of oversight and decision checkpoints.",
    nigerianAnalogy: "Weekly prep check-ins plus milestone approvals keep planning balanced.",
  },
  {
    id: "hybrid_process_integrated_planning",
    framework: "hybrid",
    domain: "process",
    topic: "integrated planning layers",
    correctStatement: "Use rolling-wave planning under an approved high-level baseline.",
    distractors: [
      "Freeze all detailed plans upfront in uncertain environments.",
      "Avoid any baseline planning in hybrid delivery.",
      "Replan everything every sprint without stable milestones.",
    ],
    textbookReference: "PMBOK 6th/7th: Rolling-wave planning and tailoring",
    formalDefinition: "Integrated planning combines long-range guardrails with near-term detail.",
    nigerianAnalogy: "Set event date and budget now, detail menus and logistics iteratively.",
  },
  {
    id: "hybrid_process_quality_controls",
    framework: "hybrid",
    domain: "process",
    topic: "hybrid quality controls",
    correctStatement: "Apply iterative quality checks while meeting mandatory audit requirements.",
    distractors: [
      "Delay quality checks to the final phase.",
      "Skip audits because agile reviews already happened.",
      "Run audits only when defects are reported by users.",
    ],
    textbookReference: "PMBOK 7th: Quality and governance domains",
    formalDefinition: "Hybrid quality management blends continuous validation with formal assurance.",
    nigerianAnalogy: "Taste often, then still pass final hygiene inspection.",
  },
  {
    id: "hybrid_process_dependency_management",
    framework: "hybrid",
    domain: "process",
    topic: "dependency management",
    correctStatement: "Map cross-team dependencies and align sprint and gate timelines.",
    distractors: [
      "Track dependencies only when delays occur.",
      "Assume parallel teams can self-synchronize without coordination.",
      "Avoid visual dependency boards to reduce overhead.",
    ],
    textbookReference: "PMI Agile Practice Guide: Hybrid coordination",
    formalDefinition: "Dependency management coordinates sequencing and handoffs across teams.",
    nigerianAnalogy: "Decorator and caterer timelines must sync or event setup fails.",
  },
  {
    id: "hybrid_process_risk_review",
    framework: "hybrid",
    domain: "process",
    topic: "risk review integration",
    correctStatement: "Review risks in iterative ceremonies and formal governance reports.",
    distractors: [
      "Review risks only during quarterly steering meetings.",
      "Keep risk updates private to project manager.",
      "Use risk list as static compliance artifact.",
    ],
    textbookReference: "PMBOK 7th: Uncertainty and risk domains",
    formalDefinition: "Integrated risk review maintains timely awareness across governance levels.",
    nigerianAnalogy: "Track weather and vendor risks weekly and at milestone briefings.",
  },
  {
    id: "hybrid_business_benefits_incremental_release",
    framework: "hybrid",
    domain: "business",
    topic: "incremental benefits release",
    correctStatement: "Release usable increments early while tracking strategic benefit milestones.",
    distractors: [
      "Hold all value until full scope is complete.",
      "Track benefits only after project closure.",
      "Prioritize internal milestones over customer outcomes.",
    ],
    textbookReference: "PMBOK 7th: Value delivery system",
    formalDefinition: "Incremental release accelerates value realization while reducing risk.",
    nigerianAnalogy: "Open services in phases so customers benefit sooner.",
  },
  {
    id: "hybrid_business_funding_decisions",
    framework: "hybrid",
    domain: "business",
    topic: "adaptive funding decisions",
    correctStatement: "Use evidence from increments to inform staged funding decisions.",
    distractors: [
      "Approve full budget once and ignore delivery evidence.",
      "Tie funding strictly to initial estimates with no review.",
      "Cut funding solely based on one missed sprint goal.",
    ],
    textbookReference: "PMBOK 7th: Governance and value evidence",
    formalDefinition: "Adaptive funding aligns investment with validated outcomes.",
    nigerianAnalogy: "Release budget in tranches after seeing clear progress and quality.",
  },
  {
    id: "hybrid_business_regulatory_alignment",
    framework: "hybrid",
    domain: "business",
    topic: "regulatory alignment",
    correctStatement: "Embed compliance checks into increments to avoid late-stage rework.",
    distractors: [
      "Handle compliance only in final integration testing.",
      "Delegate all compliance interpretation to vendors.",
      "Treat compliance as separate from product decisions.",
    ],
    textbookReference: "PMBOK 7th: Compliance and governance alignment",
    formalDefinition: "Regulatory alignment integrates constraints into delivery decisions early.",
    nigerianAnalogy: "Secure permits early, not after full setup is complete.",
  },
  {
    id: "hybrid_business_success_metrics",
    framework: "hybrid",
    domain: "business",
    topic: "hybrid success metrics",
    correctStatement: "Measure schedule and cost health alongside customer and value outcomes.",
    distractors: [
      "Use only earned value metrics in hybrid contexts.",
      "Use only customer sentiment and ignore governance metrics.",
      "Avoid metric baselines to preserve flexibility.",
    ],
    textbookReference: "PMBOK 7th: Measurement performance domain",
    formalDefinition: "Hybrid success metrics blend delivery efficiency and value realization.",
    nigerianAnalogy: "Judge event by budget discipline and guest satisfaction together.",
  },
  {
    id: "hybrid_business_operational_readiness",
    framework: "hybrid",
    domain: "business",
    topic: "operational readiness",
    correctStatement: "Prepare operations, training, and support before each major release.",
    distractors: [
      "Hand over deliverables without readiness validation.",
      "Assume users will adopt new processes without support.",
      "Delay support planning until post-deployment issues appear.",
    ],
    textbookReference: "PMBOK 7th: Delivery and transition outcomes",
    formalDefinition: "Operational readiness ensures benefits can be sustained after release.",
    nigerianAnalogy: "Train serving staff before event day so service runs smoothly.",
  },
];

function expandedQuestions(): Question[] {
  return EXPANDED_SEEDS.flatMap((seed, index) => {
    const difficulty = ((index % 5) + 1) as 1 | 2 | 3 | 4 | 5;
    const mcq = {
      id: `expanded_mcq_${seed.id}`,
      mode: "mcq" as const,
      domain: seed.domain,
      framework: seed.framework,
      difficulty,
      prompt: `In ${seed.framework.toUpperCase()} delivery, what is the BEST approach to ${seed.topic}?`,
      choices: [seed.distractors[0], seed.correctStatement, seed.distractors[1], seed.distractors[2]],
      correctChoiceIndex: 1,
      formalDefinition: seed.formalDefinition,
      textbookReference: seed.textbookReference,
      nigerianAnalogy: seed.nigerianAnalogy,
    };
    const flashcard = {
      id: `expanded_flashcard_${seed.id}`,
      mode: "flashcard" as const,
      domain: seed.domain,
      framework: seed.framework,
      difficulty,
      front: `Explain ${seed.topic} in a PMP context.`,
      back: seed.correctStatement,
      formalDefinition: seed.formalDefinition,
      textbookReference: seed.textbookReference,
      nigerianAnalogy: seed.nigerianAnalogy,
    };
    const theory = {
      id: `expanded_theory_${seed.id}`,
      mode: "theory" as const,
      domain: seed.domain,
      framework: seed.framework,
      difficulty,
      prompt: `As a PMP examiner, explain how you would apply ${seed.topic} on a ${seed.framework} project and justify the decision logic.`,
      expectedKeyPoints: [
        `State the principle clearly: ${seed.correctStatement}`,
        "Describe PMI-aligned reasoning and governance implications.",
        "Explain risk and stakeholder impact of poor execution.",
        "Provide practical next actions for implementation.",
      ],
      formalDefinition: seed.formalDefinition,
      textbookReference: seed.textbookReference,
      nigerianAnalogy: seed.nigerianAnalogy,
    };
    return [mcq, flashcard, theory];
  });
}

const COMBINED_BANK = [...(bank as Question[]), ...expandedQuestions()];

export function getQuestionBank(): Question[] {
  return COMBINED_BANK;
}

export function getQuestionById(id: string): Question | undefined {
  return COMBINED_BANK.find((q) => q.id === id);
}

